#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# STOP CONTAINER BEFORE BACKUP
#=================================================

ynh_systemctl --service="$app" --action="stop"

sleep 2

#=================================================
# BACKUP DATA DIRECTORY
#=================================================

use_data_volume=$(ynh_app_setting_get --key=use_data_volume)

if [ "$use_data_volume" -eq 1 ]; then
    ynh_backup "$data_dir"
fi

#=================================================
# BACKUP SYSTEMD SERVICE CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# RESTART CONTAINER
#=================================================

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
