#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE AND CONTAINER
#=================================================
ynh_script_progression "Removing system integrations..."

yunohost service remove "$app" 2>/dev/null || true

ynh_config_remove_systemd

if docker ps --filter "name=^${app}$" --format "{{.ID}}" 2>/dev/null | grep -q .; then
    docker stop "$app" 2>/dev/null || true
    sleep 1
fi

docker rm "$app" 2>/dev/null || true

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX configuration..."

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
